### ISSUE TITLE
A misspell in the README.md

### ISSUE THREAD

**Issue by wtllll** [cybergalactic/MSS#10]
There is A misspell in the explanation of Hydro Library the README.md. The word templastes should be changed into templates.

**Comment by cybergalactic** [comment]
Thanks. It has been fixed.

Thor

On 3 Apr 2021, at 04:17, wtllll ***@***.******@***.***>> wrote:



There is A misspell in the explanation of Hydro Library the README.md. The word templastes should be changed into templates.
