### ISSUE TITLE
Question about mariner.m

### ISSUE THREAD

**Issue by wtllll** [cybergalactic/MSS#13]
When I read the annotation about the function mariner(x,ui,U0).I found "time derivative of the state vector: x = [ u v r x y psi delta n ]'". But there is only seven parameters in x. Where is the parameter "n"? Is there a mistake?

**Comment by cybergalactic** [comment]
It is a typo. The m-file function description should be x = [ u v r x y psi delta  ], that is propeller RPM n is not used when calling mariner.m. The m-file has been updated.
