### ISSUE TITLE
Undesirable overloading of run.m

### ISSUE THREAD

**Issue by krisgry** [cybergalactic/MSS#14]
Hi,
`HYDRO/vessels_wamit/fpso/run.m` overloads the built-in matlab function `run` ([ref](https://se.mathworks.com/help/matlab/ref/run.html)). Could this be fixed by e.g. renaming?

```matlab
>> run my_own_script_not_at_all_related_to_mss.m
Attempt to execute SCRIPT run as a function:
/path/to/mss/HYDRO/vessels_wamit/fpso/run.m
```
Thanks,
Kristoffer

**Comment by cybergalactic** [comment]
The file has been renamed to run_fpso.m to avoid overloading.
