### ISSUE TITLE
run "demoOtherUSVHeadingControl" error,maybe exist problem

### ISSUE THREAD

**Issue by openye** [cybergalactic/MSS#16]
![image](https://user-images.githubusercontent.com/53599830/125039193-cea60580-e0c8-11eb-8d1e-529541bdf3ab.png)

**Comment by cybergalactic** [comment]
The Simulink file is running on my computer. Can you double check that you have downloaded the latest version of the m-files and Simulink files from GitHub. Also double check that all MSS files are on your Matlab path. The otter.m file should return xdot and U. You can test this using the call Matlab command: [xdot,U] = otter(zeros(12,1),[0 0]',1,[0 0 0]',1,1). Then report back.

**Comment by openye** [comment]
My version of MATLAB is 2021a. After I add an external declaration, the program can be executed. Thank you very much, Professor fossen.
![image](https://user-images.githubusercontent.com/53599830/125245007-98fc5900-e322-11eb-9452-4c44259370d8.png)
![image](https://user-images.githubusercontent.com/53599830/125245782-8c2c3500-e323-11eb-9192-ecb7e054623d.png)

**Comment by cybergalactic** [comment]
You are welcome.
