### ISSUE TITLE
q2euler.m: 'theta' is not assigned on some execution paths.

### ISSUE THREAD

**Issue by sifhognadottir2** [cybergalactic/MSS#20]
Hi, 
The addition of the if-statement in q2euler.m to handle NaN due to round-off errors causes Simulink to give an error: "Output argument 'theta' is not assigned on some execution paths.".

Regards,
Sif Högnadottir

**Comment by wtllll** [comment]
您好，已收到您的邮件，谢谢！

**Comment by cybergalactic** [comment]
Fixed
