### ISSUE TITLE
How to get hydrodynamic derivatives from vessel struct? 

### ISSUE THREAD

**Issue by MeetGandhi-Honda** [cybergalactic/MSS#26]
Hey @cybergalactic,

I am trying to use MSS with my own vessel. For the same, I want to know how to get the hydrodynamic derivatives (https://github.com/cybergalactic/MSS/blob/master/VESSELS/mariner.m#L57-L73) from the vessel struct (For instance, https://github.com/cybergalactic/MSS/blob/master/HYDRO/vessels_wamit/tanker/tanker.mat). I am asking as the vessel structure does not have variables with names associated to the hydrodynamic derivatives. Is there a way to extract the hydrodynamic derivatives from the vessel struct?

I am looking forward to your response.
Regards

**Comment by cybergalactic** [comment]
It is temporary maintenance of the web server. The site will be up and running on April 25.

On 20 Jul 2022, at 15:42, MeetGandhi-Honda ***@***.******@***.***>> wrote:



Hey @cybergalactic<https://github.com/cybergalactic>,

I was able to load lecture slides (https://www.fossen.biz/wiley/) a few days back; however now I cannot. Is there a way to get hold of those slides?

Regards
