### ISSUE TITLE
Find a problem in mariner.m

### ISSUE THREAD

**Issue by wtllll** [cybergalactic/MSS#27]
In the file of mariner.m,line 86 .There is an equation"delta_dot = delta_c - delta;",using this equation to calculate the change rate of the rudder,but this equation doesn't take the time  integration time into account.If the integation time is not equal to one sec,then the equation is wrong,am I right?

**Comment by cybergalactic** [comment]
Yes, you are correct. You can change this equation and add a time constant different from 1 second.
