### ISSUE TITLE
find a problem in container.m

### ISSUE THREAD

**Issue by wtllll** [cybergalactic/MSS#28]
In container.m line132 there is an equation "uP     = cos(v)*((1 - wp) + tau*((v + xp*r)^2 + cpv*v + cpr*r));" .But I found the same equation in the reference "Son og Nomoto (1982). On the Coupled Motion of Steering and Rolling of a High Speed Container Ship, Naval Architect of Ocean Engineering,20: 73-83. From J.S.N.A. , Japan, Vol. 150, 1981.",but the equation is 
![image](https://user-images.githubusercontent.com/45661476/181239504-c5954c5e-cd0a-4ac4-9bed-fade2bf1dbe7.png)
,so "cos(v)" should change into "u".

**Comment by cybergalactic** [comment]
Thanks for reporting the bug. An updated version of container.m has been uploaded.
