### ISSUE TITLE
How to build my own model of vessel

### ISSUE THREAD

**Issue by djmv** [cybergalactic/MSS#3]
Thanks for the toolbox, It is amazing! 
I'm interested in building a model of my vessel. I'm a student and want simulate my vessel RC. In toolbox there is a model of Mariner and other ship, there is some way to build a 3 dof model of any ship? How compute the values?, there is an script or something else that help me to build a model for my vessel? Thanks @cybergalactic 

For example in mariner.m is the model of this kind of ship, there a way to build some similar but with other ship?

**Comment by cybergalactic** [comment]
To build a model like the mariner.m you need to study hydrodynamics and learn how to configure/run hydrodynamic programs.
