### ISSUE TITLE
The Otter model's Yv is 0, which may cause a non-converged roll curve  when i add an addtional  force in Y direction

### ISSUE THREAD

**Issue by JasonWang2333** [cybergalactic/MSS#35]
Sorry for trouble again, but when i checked the 'Otter.m' model this evening,  i put an load in the Y direction in the body-fixed coordinate system the roll angel and sway velocity is going to be larger and larger, so i looked over the code and find that in the 'Linear damping terms', the Yv is set to 0, i guess the reason behind the phenomenon  is the damping coefficient is set to 0, so i try to copy the Xu 's  expression to Yv and run the simulation,then i found the roll angle and the sway velocity is converged to 0 but slowly. 
Accordingly, i want to know if i am right. If so, i also want to know how to set the Yv(Yv's expression) or how to deal the situation.

**Comment by cybergalactic** [comment]
This is not happening when I run the code. Can you explain how you specify the load in the y-direction when you test the scripts? Are you running the latest version of otter.m and SIMotter.m on GitHub?

The reason that Yv = 0 is that cross-flow drag is included in the model. This gives additional damping in sway and yaw. However, you can include a small linear damping coefficient Yv to improve convergence to zero.

**Comment by JasonWang2333** [comment]
Thanks for your answer.
Yes, i run the lateset version of' Otter.m'. I set the load (or force) to the point of orgin point O [0,0,0], then set the force = [0,-80,0]'(N), then the response image of the is as follow:
[
![image](https://user-images.githubusercontent.com/102033219/228711771-26025e78-195e-4e85-9d50-ea40ca7ca85a.png)](url)
 As i explain in the last commend, the simulation result of roll velocity and roll angle seems strange, in a longer simulation time version,  you can see the amplitude of them seems even to be lager:
[
![image](https://user-images.githubusercontent.com/102033219/228713341-1b574fff-331a-45c2-bbdf-3d53bdaf56ac.png)](url)
 By the way,  whether 'a small linear damping coefficient Yv ' means i could test it by myself?

**Comment by JasonWang2333** [comment]
Just to add some information, the force i use is a step force, which only lasts for **3 seconds.**

**Comment by cybergalactic** [comment]
If I use a step in the payload (80 N at time t = 0) in SIMotter.m, 

mp = 80/9.81;      % payload mass (kg), max value 45 kg
rp = [0 0 0]';        % location of payload (m)

the otter.m model is stable. In general, a large step can be a problem when using Euler's integration method. You should consider low-pass filtering all step inputs. You can, of course, add a non-zero value for Yv to improve damping in sway. A guideline could be to choose

Yv = - (m - Yv_dot) / T_sway

where T_sway is the time constant in sway (typically 10-20 s); see Equation (15.107) in my 2021 Wiley textbook.
<img width="494" alt="velocity" src="https://user-images.githubusercontent.com/43878665/228751347-8442d659-ec29-4f66-a9a0-a735d82d5b8a.png">

**Comment by cybergalactic** [comment]
You can also test a step in the sway force by modifying the otter.m file. If you add the payload -80 N in sway

g_0 = [ fp + [0 0 -80/9.81]'
            mp ];

the response is still stable

<img width="494" alt="Screenshot 2023-03-30 at 08 51 02" src="https://user-images.githubusercontent.com/43878665/228753109-4d1f61cd-ca7f-43e0-9c16-cacbff8fa528.png">

**Comment by JasonWang2333** [comment]
OK，thanks,  I get your meaning.  
I will bother you later if i find something wrong with the code.

**Comment by yujian950322** [comment]
可以留一下 邮箱吗？有问题想问您

**Comment by wtllll** [comment]
您好，已收到您的邮件，谢谢！
