### ISSUE TITLE
Control-Autopilost model

### ISSUE THREAD

**Issue by VastSeaL** [cybergalactic/MSS#41]
Hi Prof. Fossen,

I use the "Course autopilot" module in the MSS Simulink Library /Control/Autopilots. Can you help me to explain how the module work? Besides,  where is the source code of the module?

Thank you very much.

**Comment by cybergalactic** [comment]
You find the Simulink library blocks after typing: >>mssSimulink, in the Matlab workspace. The course autopilot is based on Algorithm 15.1 in my Wiley (2021) textbook. This is a SISO PID pole-placement algorithm for vehicles. You will also find the algorithm in my lecture notes, which can be downloaded from [https://wiley.fossen.biz]. The design of heading and course autopilots are explained in detail in my book; see Chapters 7 and 15.3.4.
