### ISSUE TITLE
Can I use MSS for simulating free falling objects under water?

### ISSUE THREAD

**Issue by huisky2000** [cybergalactic/MSS#44]
Dear Prof. Fossen,

The free falling of an object underwater should be much easier, no power and no target. Isn't it? 
Can I make the simulation by some 'simple' modification to the code?

Regards
Huisky

**Comment by cybergalactic** [comment]
If you put all control signals to zero in SIMremus100.m the AUV will sink if and only if the weight is larger than the buoyancy force. You can increase the mass in remus100.m, which contains the AUV model. Note that the AUV is cylinder-shaped, but it will sink like a rock.
