### ISSUE TITLE
Is there any model descriptions in VESSELS folder?

### ISSUE THREAD

**Issue by tcjcxy30** [cybergalactic/MSS#49]
Hi: 
   Thanks for the MSS projects. Where can I find the model description for each file in VESSELS folder? I am looking for a model with only one thruster and one rudder. Which file should I refer to?

**Comment by cybergalactic** [comment]
There are no model descriptions except the comments in the m-files. The models are based on the methods described in my Wiley textbook from 2021. There are ship models with one main engine and one rudder, which can be used. Note that you can change the m-files and add your own propulsion systems.

**Comment by tcjcxy30** [comment]
> There are no model descriptions except the comments in the m-files. The models are based on the methods described in my Wiley textbook from 2021. There are ship models with one main engine and one rudder, which can be used. Note that you can change the m-files and add your own propulsion systems.

Dear Professor Fossen :
Thank you for your reply. May I ask what the file name for the model is?

**Comment by cybergalactic** [comment]
You can use one of the ship models:

clarke83        % linear maneuvering model parametrized using (L,B,T) found from linear regression of model tests
container       % nonlinear maneuvering model of a high-speed container ship, L = 175 m, including roll
mariner         % nonlinear maneuvering model for the Mariner class vessel, L = 160 m 

Time-series simulation

SIMclarke83     % simulate clarke83.m under PD control
SIMcontainer    % simulate container.m and Lcontainer.m under PD control
SIMmariner      % simulate mariner.m under PD control
