### ISSUE TITLE
Munk moments

### ISSUE THREAD

**Issue by joaobrittoneto** [cybergalactic/MSS#50]
Hi Prof. Fossen,

While having a look at Munk moments and it's destabilizing effect on simulation of UUVs, I came across [this](https://github.com/cybergalactic/MSS/blob/master/VESSELS/remus100.m#L184-L187) simplification for the Remus. I believe the term [CA(5,4)](https://github.com/cybergalactic/MSS/blob/master/VESSELS/remus100.m#L185) was supposed to be `CA(5,3)`, referring to term `-X_udot * u_r` in equation [6.54 (1st edition) or 6.60 (2nd)](https://github.com/cybergalactic/FossenHandbook/tree/main).

For my case, I'll need to do a similar approach to compensate for the unmodeled nonlinear damping, and I was wondering if it could be generalized also for the roll part (i.e. CA(4,2) and CA(4,3)), zeroing the whole bottom left part of the CA matrix. Any though on that?

Best regards

**Comment by wtllll** [comment]
您好，已收到您的邮件，谢谢！
