### ISSUE TITLE
Ship Irregular ZigZag Maneuvering Test

### ISSUE THREAD

**Issue by wanghengshine** [cybergalactic/MSS#53]
Dear Professor,

How can I configure the ExZagzig file you published so that the ship model can perform irregular ZigZag tests? I attempted to change only the rudder angle, but it was ineffective.

**Comment by cybergalactic** [comment]
The example script ExZigzag.m demonstrates how you can change the rudder angle, e.g., 20-10 maneuver, using the Matlab function

zigzag('container',x,ui,t_final,t_rudderexecute,0.1,[20,10]);

If you want to achieve something else than basic rudder commands, you need to make a copy of the file zigzag.m, save it as myZigzag.m, and add your own code to achieve this.
