### ISSUE TITLE
U problem in "otter.m" and "SIMotter.m"

### ISSUE THREAD

**Issue by JasonWang2333** [cybergalactic/MSS#55]
I’d like to point out a question in "otter.m"and "SIMotter.m"
'U = sqrt(nu(1)^2 + nu(2)^2 + nu(3)^2);      % speed'
if this is used for LOS guidance law or etc., then the U means the total speed of  horizontal motion ,so I think this should be replaced by:
'U = sqrt(nu(1)^2 + nu(2)^2 );      % speed'
cause in the LOS, the U defines as :
![image](https://github.com/cybergalactic/MSS/assets/102033219/46b8dffb-618b-4119-905e-716367f85e6f)

**Comment by cybergalactic** [comment]
The 3-D speed for an USV will be very close to the horizontal 2-D speed so you might not see a difference. Anyway, if you use a 2-D LOS algorithm (xy plane), I agree that the 2-D speed is more correct to use.  Many LOS guidance laws do not use the speed at all but if you need the 2-D speed you can modify the function to return the 2-D value as an argument.

- Thor

On 22 Mar 2024, at 09:46, JasonWang2333 ***@***.***> wrote:



I’d like to point out a question in "otter.m"and "SIMotter.m"
'U = sqrt(nu(1)^2 + nu(2)^2 + nu(3)^2); % speed'
if this is used for LOS guidance law or etc., then the U means the total speed of horizontal motion ,so I think this should be replaced by:
'U = sqrt(nu(1)^2 + nu(2)^2 ); % speed'
cause in the LOS, the U defines as :
image.png (view on web)<https://github.com/cybergalactic/MSS/assets/102033219/46b8dffb-618b-4119-905e-716367f85e6f>

**Comment by JasonWang2333** [comment]
Thanks.
