### ISSUE TITLE
Why is M_A in 'Otter.m'  a diagonal matrix？

### ISSUE THREAD

**Issue by JasonWang2333** [cybergalactic/MSS#59]
but in ur text book, 'the vehicle also has three planes of symmetry', when the M_A is a diagonal matrix. 
![image](https://github.com/cybergalactic/MSS/assets/102033219/92e081ba-6dcb-482d-a625-9faa97c611da)
 and i check the USV doesn't has three planes of symmetry:
![image](https://github.com/cybergalactic/MSS/assets/102033219/260e8df3-ff9d-4883-a50c-3252fa2a8c9d)
what's the reason of simplifying this matrix?

**Comment by cybergalactic** [comment]
The process of purchasing a hydrodynamic program and creating a 3D drawing for hydrodynamic computations is both time-consuming and costly. Alternatively, you could compute the 6x6 added mass matrix using these methods, or you might opt for simplified semi-empirical approaches. For surface vehicles like the Otter USV, there is port-starboard symmetry. The submerged hull exhibits nearly perfect fore-aft and top-bottom symmetry, with the exception of appendages like propellers. Therefore, it's feasible to model this as having 3-plane symmetry and utilize a diagonal MA matrix, where the off-diagonal elements are significantly smaller than the diagonal ones.

**Comment by JasonWang2333** [comment]
Thanks a lot. I get it.
