### ISSUE TITLE
IDENTIFICATION OF DYNAMICALLY POSITIONED SHIPS paper

### ISSUE THREAD

**Issue by tahmine-iaun** [cybergalactic/MSS#6]
I am  MSc student in Control engineering  
I have recently came across your quite interesting papers “ IDENTIFICATION OF DYNAMICALLY POSITIONED SHIPS ”  I wonder if there exists any source code or other useful documents . And if so, I appreciate if you kindly let me know how I can have access to them I need those information to be able to validate my method . I need to compare my results to the correct values.

**Comment by cybergalactic** [comment]
Sorry, no source code. Just the numerical values in the paper.
