### ISSUE TITLE
possibility to add simulation model for paper "Line‑of‑sight path‑following control utilizing an extended Kalman filter for estimation of speed and course over ground from GNSS positions"

### ISSUE THREAD

**Issue by LiangZhao13** [cybergalactic/MSS#60]
Dear professor Fossen, I recently read your publication "Line‑of‑sight path‑following control utilizing an extended Kalman filter for estimation of speed and course over ground from GNSS positions" in JMST. The paper described a complete and detailed model of the application for GNC system. I was wondering is it possible to add the simulation model in the paper to the MSS toolbox in the next release?

**Comment by cybergalactic** [comment]
I have included the SImulink file "demoMarinerPathFollowingCourseControl.slx"  representing the case study in JMST. Later, I will also add an m-file version of the case study.

**Comment by cybergalactic** [comment]
SIMmariner.m is now available to simulate 2-D LOS path-following control using a course autopilot based on pole placement. The m-file is implemented similarly to the Simulink block diagram "demoMarinerPathFollowingCourseControl. slx".

**Comment by LiangZhao13** [comment]
Thank you so much for providing those demos !!!!
