### ISSUE TITLE
how to customize a ship

### ISSUE THREAD

**Issue by hakieh** [cybergalactic/MSS#67]
Hello, I am very interested in your work and I want to customize a ship. What are the specific definitions of some of the parameters mentioned in those files in folder VESSELS. [supply.m](https://github.com/cybergalactic/MSS/blob/master/VESSELS/models/supply.m)  
 If there are any references that can be read I would be very grateful to you for telling me！

**Comment by cybergalactic** [comment]
The supply.m is a very basic model. You can customize and build your ship by using osv.m and SIMosv.m instead. The functions in the script are described in my lecture notes and textbook.
